In [1]:
import pandas as pd

In [2]:
INPUT_DIR = "input/artifacts"
ENTITY_TABLE = "create_final_nodes"
ENTITY_EMBEDDING_TABLE = "create_final_entities"
RELATIONSHIP_TABLE = "create_final_relationships"
COMMUNITY_REPORT_TABLE = "create_final_community_reports"
TEXT_UNIT_TABLE = "create_final_text_units"
DOCUMENTS_TABLE = "create_final_documents"

In [7]:
documents = pd.read_parquet(f'{INPUT_DIR}/{DOCUMENTS_TABLE}.parquet')

In [10]:
documents.head()

,id,text_unit_ids,raw_content,title
0,42956fcce30f1478d0bc04dd22bc126c,"[f6302f2937ee65b7474c3e6abcfc096b, 93e2564e6fd...",`About us\nServices \nSoftware Testing\nAutoma...,tft.txt

In [11]:
documents.shape

(1, 4)

In [12]:
text_chunks = pd.read_parquet(f'{INPUT_DIR}/{TEXT_UNIT_TABLE}.parquet')

In [13]:
text_chunks.shape

(7, 6)

In [14]:
text_chunks.head(10)

,id,text,n_tokens,document_ids,entity_ids,relationship_ids
0,f6302f2937ee65b7474c3e6abcfc096b,`About us\nServices \nSoftware Testing\nAutoma...,300,[42956fcce30f1478d0bc04dd22bc126c],"[b45241d70f0e43fca764df95b2b81f77, 4119fd06010...","[404309e89a5241d6bff42c05a45df206, b785a902506..."
1,93e2564e6fd31bdf22aa6f1ac928de0c,", enabling them to achieve superior business o...",300,[42956fcce30f1478d0bc04dd22bc126c],"[19a7f254a5d64566ab5cc15472df02de, e7ffaee9d31...","[958beecdb5bb4060948415ffd75d2b03, b999ed77e19..."
2,5d4697ed3a13c4dd29c43175f49af417,Teamwork\nContinuous Improvements\nOur Success...,300,[42956fcce30f1478d0bc04dd22bc126c],"[19a7f254a5d64566ab5cc15472df02de, f7e11b0e297...","[b999ed77e19e4f85b7f1ae79af5c002a, 48c0c4d72da..."
3,485ed2ff04816c57eea475488d928826,\n\nEasy and low-cost migration of your automa...,300,[42956fcce30f1478d0bc04dd22bc126c],"[e7ffaee9d31d4d3c96e04f911d0a8f9e, c9632a35146...","[9ab48505fb1b487babd0d1f6d3a3f980, 148fffeb994..."
4,42281787cd51507a2818e22b4a2412d1,Priyesh\nQA Lead\nPrashant\nAssociate QA Manag...,300,[42956fcce30f1478d0bc04dd22bc126c],"[19a7f254a5d64566ab5cc15472df02de, 3d6b216c143...","[1033a18c45aa4584b2aef6ab96890351, c9b8ce91fc2..."
5,49b02b4611b1532f3f702fc352b48655,needs and culture.\n\nDedicated Teams\nTrue P...,300,[42956fcce30f1478d0bc04dd22bc126c],"[f1c6eed066f24cbdb376b910fce29ed4, 83a6cb03df6...","[482027a59f32484c9c44fd700615c1b6, de837ff3d62..."
6,3b353c74665dbf0beb5c500237ae5493,About\nWho we are\nCareers\nServices\nPrivacy ...,108,[42956fcce30f1478d0bc04dd22bc126c],"[f1c6eed066f24cbdb376b910fce29ed4, 83a6cb03df6...","[482027a59f32484c9c44fd700615c1b6, de837ff3d62..."

In [15]:
entities = pd.read_parquet(f'{INPUT_DIR}/{ENTITY_EMBEDDING_TABLE}.parquet')

In [16]:
entities.shape

(55, 8)

In [18]:
entities.head(10)

,id,name,type,description,human_readable_id,graph_embedding,text_unit_ids,description_embedding
0,b45241d70f0e43fca764df95b2b81f77,"""THINK FUTURE TECHNOLOGIES""","""ORGANIZATION""","""Think Future Technologies (TFT) is a technolo...",0,None,[f6302f2937ee65b7474c3e6abcfc096b],"[-0.03396954759955406, -0.04939436912536621, 0..."
1,4119fd06010c494caa07f439b333f4c5,"""GITEX DUBAI 2023""","""EVENT""","""Gitex Dubai 2023 is an event where technology...",1,None,[f6302f2937ee65b7474c3e6abcfc096b],"[-0.009415441192686558, -0.021130401641130447,..."
2,d3835bf3dda84ead99deadbeac5d0d7d,"""ARTIFICIAL INTELLIGENCE""","""TECHNOLOGY""","""Artificial Intelligence (AI) is one of the ke...",2,None,[f6302f2937ee65b7474c3e6abcfc096b],"[-0.021639185026288033, -0.01954113505780697, ..."
3,077d2820ae1845bcbb1803379a3d1eae,"""BLOCKCHAIN""","""TECHNOLOGY""","""Blockchain is another area of specialization ...",3,None,[f6302f2937ee65b7474c3e6abcfc096b],"[-0.007738661952316761, -0.0435759611427784, -..."
4,3671ea0dd4e84c1a9b02c5ab2c8f4bac,"""IOT""","""TECHNOLOGY""","""IoT (Internet of Things) is a technology area...",4,None,[f6302f2937ee65b7474c3e6abcfc096b],"[-0.0354221872985363, -0.005053800065070391, -..."
5,19a7f254a5d64566ab5cc15472df02de,"""TFT""","""ORGANIZATION""",TFT is a technology organization that speciali...,5,None,"[42281787cd51507a2818e22b4a2412d1, 5d4697ed3a1...","[-0.03301558643579483, -0.0399981290102005, 0...."
6,e7ffaee9d31d4d3c96e04f911d0a8f9e,"""VIJAY""","""PERSON""","Vijay is a key figure at TFT, serving as both ...",6,None,"[485ed2ff04816c57eea475488d928826, 93e2564e6fd...","[-0.008027715608477592, -0.025529926642775536,..."
7,f7e11b0e297a44a896dc67928368f600,"""MEXICO""","""GEO""",Mexico is a geographical location where TFT ha...,7,None,"[5d4697ed3a13c4dd29c43175f49af417, 93e2564e6fd...","[-0.03363178297877312, 0.03233034908771515, 0...."
8,1fd3fa8bb5a2408790042ab9573779ee,"""THE UNICODE CONSORTIUM""","""ORGANIZATION""",The Unicode Consortium is an organization that...,8,None,"[5d4697ed3a13c4dd29c43175f49af417, 93e2564e6fd...","[-0.02911612018942833, -0.04950232431292534, 0..."
9,27f9fbe6ad8c4a8b9acee0d3596ed57c,"""2023""","""EVENT""","""2023 marks a significant year for TFT, indica...",9,None,[93e2564e6fd31bdf22aa6f1ac928de0c],"[-0.007358199451118708, -0.03383808210492134, ..."